name: HACS validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run HACS action
        uses: hacs/action@main
        env:
          REPOSITORY_REF: ${{ github.head_ref || github.ref_name }}
        with:
          category: integration
